#!/bin/bash
echo "🚀 Запуск DevOps стека..."
docker-compose up -d
echo ""
echo "✅ Стек запущен!"
echo ""
echo "📊 Доступные сервисы:"
echo "• Prometheus: http://localhost:9090"
echo "• Grafana: http://localhost:3000 (admin/admin123)"
echo "• Loki: http://localhost:3100"
echo "• Alertmanager: http://localhost:9093"
echo "• Node Exporter: http://localhost:9100"
echo "• PostgreSQL: localhost:5432 (devops/devops123)"
echo "• Redis: localhost:6379"
echo "• MinIO: http://localhost:9001 (admin/admin123)"
echo "• Vault: http://localhost:8200"
echo "• Gotify: http://localhost:8081"
echo "• Jenkins: http://localhost:8080"
echo ""
echo "🔧 Управление:"
echo "• Статус: ./monitor-stack.sh"
echo "• Остановка: ./stop-stack.sh"
echo "• Логи: docker-compose logs -f"
