global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@devops.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://gotify:80/message'
        send_resolved: true
